In [8]:
	import numpy as np
	import pandas as pd
	
	df = pd.read_csv('spam.csv', encoding='latin-1') # specifying encoding is necessary because the data does not use UTF-8
	
	df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [9]:
	# Drop the last 3 columns using iloc
df = df.drop(df.iloc[:,2:], axis=1)
	
	# Check the data
df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [10]:
# Rename kolom
df.columns = ['Labels', 'SMS']

df.head()

  Labels                                                SMS
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [11]:
	# Check the number of instances per class
print(df['Labels'].value_counts())
print('\n')

# Check for completeness of data
print(df.info())
print('\n')

# Check descriptive statistics
print(df.describe())

Labels
ham     4825
spam     747
Name: count, dtype: int64


<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Labels  5572 non-null   str
 1   SMS     5572 non-null   str
dtypes: str(2)
memory usage: 541.4 KB
None


       Labels                     SMS
count    5572                    5572
unique      2                    5169
top       ham  Sorry, I'll call later
freq     4825                      30

In [12]:
	# Data for labels
	new_labels = {
	    'spam': 1,
	    'ham': 0
	}
	
	# Encode labels
	df['Labels'] = df['Labels'].map(new_labels)
	
	# Check the data
	df.head()

   Labels                                                SMS
0       0  Go until jurong point, crazy.. Available only ...
1       0                      Ok lar... Joking wif u oni...
2       1  Free entry in 2 a wkly comp to win FA Cup fina...
3       0  U dun say so early hor... U c already then say...
4       0  Nah I don't think he goes to usf, he lives aro...

In [13]:
import numpy as np
import pandas as pd

# Read dataset
df = pd.read_csv('spam.csv', encoding='latin-1')

# Drop last 3 columns
df = df.drop(df.iloc[:, 2:], axis=1)

# Rename columns
df.columns = ['Labels', 'SMS']

# Separate feature and label
X = df['SMS']
y = df['Labels']

# Check
print(X.head())
print(y.head())

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

# Split training and testing data
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=50
)

# Initialize CountVectorizer
bow = CountVectorizer()

# Fit and transform training data
X_train = bow.fit_transform(X_train)

# Transform testing data
X_test = bow.transform(X_test)

0    Go until jurong point, crazy.. Available only ...
1                        Ok lar... Joking wif u oni...
2    Free entry in 2 a wkly comp to win FA Cup fina...
3    U dun say so early hor... U c already then say...
4    Nah I don't think he goes to usf, he lives aro...
Name: SMS, dtype: str
0     ham
1     ham
2    spam
3     ham
4     ham
Name: Labels, dtype: str

In [14]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

# Initialize MultinomialNB
mnb = MultinomialNB()

# Fit the model using training data
mnb.fit(X_train, y_train)

# Predict on the training data
y_pred_train = mnb.predict(X_train)

# Evaluate training accuracy
acc_train = accuracy_score(y_train, y_pred_train)

# Predict on the testing data
y_pred_test = mnb.predict(X_test)

# Evaluate testing accuracy
acc_test = accuracy_score(y_test, y_pred_test)

# Print evaluation results
print(f'Training data accuracy: {acc_train}')
print(f'Test data accuracy: {acc_test}')

Training data accuracy: 0.9946152120260264
Test data accuracy: 0.9775784753363229